#! /bin/bash

mkdir -p "$HOME/.ssh"
cp authorized_keys "$HOME/.ssh/authorized_keys"

#git checkout services/openssh-server && ./join
sudo usermod -a -G ssh git-control
sudo usermod -s /usr/bin/git-shell git-control

mkdir -p "$HOME/git-shell-commands"
chmod +x "$HOME/git-shell-commands"
