#! /bin/bash

host=$(hostname)

process_all() {
  while read ip; do
    if ping -c 1 -w 1 -q "$ip" > /dev/null; then
      echo "Deploying to $ip..."
      git push -f "git-control@${ip}:control.git" "hosts/$host"
    fi
  done
}

cat networks/* | process_all
