#! /bin/bash

host=$(hostname)

echo "Joining this machine to your GC network as 'hosts/$host'"

git checkout host
./leave

(git checkout "hosts/$host" && echo "re-used existing configuration") || (echo "creating new configuration..." && git checkout -b "hosts/$host")

hostid=$(cat /etc/machine-id)
date=$(date)

touch .joins
echo "$hostid -- $date" >> .joins
git add .joins
git commit -m "Host $host (id: $hostid) joined on $date"

./join

#git push --set-upstream origin "hosts/$host"

git checkout main
