#! /bin/bash

# network join script

host=$(hostname)

function register_each_gateway() {
  while read gw; do
    echo "Joining: $gw"
    git checkout "network/$gw" || git checkout -B "network/$gw"
    git subtree add --prefix="hosts/$host" "hosts/$host"
    git commit -m "Host $host joined network $gw"
  done
}

route -n | grep 'UG[ \t]' | awk '{print $2}' | register_each_gateway
