#! /usr/bin/env bash

function test () {
  if [ ! -f "$file.test" ]; then 
    echo "MISSING TEST: $file.test" 1>&2 
    exit 1
  fi
  echo "Testing: $file"
  "$file.test"
}

function each_file () {
  while read file; do
    if [[ "$file" != *test ]]; then
      test || exit 1
    fi
  done
}

git diff HEAD --name-only | each_file
